#!/bin/bash -ex

if [ -z "$TAG" ]
then
  if ! git describe --exact-match --tags > /dev/null 2>&1
  then
    TAG="latest"
  else
    TAG=$(git describe --exact-match --tags | tr ' ' '\n' | head -1)
  fi
else
  echo "$0: TAG is already explicitly set to '$TAG' - using this one, then"
fi

CFG="$HOME/.config/eagle_cad"
mkdir -p "$CFG"

xhost "+si:localuser:$USER"

docker run \
  -it --rm \
  --read-only \
  --name="eagle_$USER" \
  --network=none \
  -u "$(id -u):$(id -g)" \
  -e DISPLAY="$DISPLAY" \
  -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
  -v "$HOME/prjs:/mnt/prjs/" \
  -e "HOME=/home/user" \
  -v "$CFG:/home/user/" \
  -e QT_X11_NO_MITSHM=1 \
  "baszerr/eagle_cad:$TAG" "$@"
